---
title: "Exacto 2023-112 A92 ANOVA Biomass"
author: "Felipe Faleco"
date: "2022-09-09"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(car)
library(dplyr)
library(glmmTMB)
library(DHARMa)
library(emmeans)
library(ggplot2)


```


# PREPARING DATA

```{r}

data <- read.csv("Data Sheet_2023-112_A90.csv")


data <- data %>% filter(rate == "140" | rate == "280" | rate == "560")



str(data)

data$run <- as.factor(data$run)

data$trt <- as.factor(data$trt)

data$pop <- as.factor(data$pop)

data$herb <- as.factor(data$herb)

data$rate <- as.factor(data$rate)

data$rep <- as.factor(data$rep)

str(data)

```


# MODEL

```{r}

model <- glmmTMB(biored ~ herb * rate, data = data, family = beta_family())


```



# CHECKING ASSUMPTIONS

```{r}

summary(model)

resid <- simulateResiduals(model)

plot(resid)

```



# ANOVA

```{r, echo=TRUE}

glmmTMB:::Anova.glmmTMB(model)

```



# EMM & CLD

```{r, echo=TRUE}

emm_rate <- emmeans(model, ~ rate, adjust = "tukey", type = "response", contr = "pairwise")

emm_rate


CLD_emm_rate <- if(requireNamespace("multcomp")) {
    multcomp::cld(emm_rate$emmeans, alpha = 0.05, Letters=letters, adjust="tukey", reversed = TRUE)}

CLD_emm_rate



emm_herb <- emmeans(model, ~ herb, adjust = "tukey", type = "response", contr = "pairwise")

emm_herb

CLD_emm_herb <- if(requireNamespace("multcomp")) {
    multcomp::cld(emm_herb$emmeans, alpha = 0.05, Letters=letters, adjust="tukey", reversed = TRUE)}

CLD_emm_herb


```



# PLOT

```{r, echo=TRUE}

plot(emm_rate, adjust = "tukey", comparisons = T, CIs = F, alpha = 0.1,  horizontal = T) + 
  geom_point(size = 2) +
  geom_text(aes(label = c("c", "b", "a")),
            vjust = -0.8, size = 4) +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), limits = c(0, 1),
    labels = scales::percent_format(scale = 100, suffix = "")) +
  labs(#title = "Waterhemp Biomass Reduction - POST", 
       x = "Biomass Reduction (%)", 
       y = "Herbicide Rate") +
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 18, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 18, colour = "darkgreen"), 
         axis.text= element_text(face = "bold", size = 14, colour = "black")) +
  ggsave("2023-112_A90_ANOVA Biomass_RATE.tiff", units="in", width = 8, height = 6, dpi = 600, compression = "lzw")





plot(emm_herb, adjust = "tukey", comparisons = T, CIs = F, alpha = 0.1,  horizontal = T) + 
  geom_point(size = 2) +
  geom_text(aes(label = c("a", "b")),
            vjust = -0.8, size = 4) +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), limits = c(0, 1),
    labels = scales::percent_format(scale = 100, suffix = "")) +
  labs(#title = "Waterhemp Biomass Reduction - POST", 
       x = "Biomass Reduction (%)", 
       y = "Herbicide") +
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 18, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 18, colour = "darkgreen"), 
         axis.text= element_text(face = "bold", size = 14, colour = "black")) +
  ggsave("2023-112_A90_ANOVA Biomass_HERB.tiff", units="in", width = 8, height = 6, dpi = 600, compression = "lzw")



```





