---
title: "RAW BIORED - GIANT RAGWEED POP x HERB"
author: "Felipe A. Faleco"
date: "01/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)

```


# WHOLE DATA

```{r}

giant_rag <- read.csv("All POST_Reduction.csv")

str(giant_rag)

giant_rag$run <- as.factor(giant_rag$run)

giant_rag$pop <- as.factor(giant_rag$pop)

giant_rag$herb <- as.factor(giant_rag$herb)

giant_rag$rate <- as.factor(giant_rag$rate)

giant_rag$rep <- as.factor(giant_rag$rep)

str(giant_rag)

```


# 1X

```{r}

giant_rag_1x <- giant_rag %>% filter(rate == "1x")

```



## DATA SUMMARY

```{r}

summary_1x <- giant_rag_1x %>% 
  group_by(pop, herb) %>% 
  summarise(n = sum(!is.na(bio_red)), 
            mean = mean(bio_red, na.rm = TRUE), 
            sd = sd(bio_red, na.rm = TRUE),
            se = sd / sqrt(n),
            CI = qnorm(1- 0.05/2) * se)

summary_1x$herb <- factor(summary_1x$herb,
                       levels = c("glyphosate", "cloransulam", "fomesafen"))

summary_1x
            
```



## PLOT

```{r}

ggplot(summary_1x, aes(x = mean*100, y = pop)) + 
  xlim(0, 100) + 
  geom_point(size = 2.5) + 
  geom_vline(xintercept = 90, size = 1, colour = "red") +
  geom_errorbar(aes(xmin = (mean*100) - (se*100), xmax = (mean*100) + (se*100), width = 0.3)) + 
  facet_grid( ~ herb, labeller = label_value) +
  labs(title = "Giant Ragweed Biomass Reduction - 1x POST", x = "Biomass Reduction (%)", y = "Population") + 
  theme_dark() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 35, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 25, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 15, colour = "black"),
         strip.text = element_text(face = "bold", size = 23, colour = "white")) +
  ggsave("RAW_POPxHERB_COMBINED_1x.jpeg", units="in", width = 15, height = 8, dpi=600)


```



# 3X

```{r}

giant_rag_3x <- giant_rag %>% filter(rate == "3x")

```



## DATA SUMMARY

```{r}

summary_3x <- giant_rag_3x %>% 
  group_by(pop, herb) %>% 
  summarise(n = sum(!is.na(bio_red)), 
            mean = mean(bio_red, na.rm = TRUE), 
            sd = sd(bio_red, na.rm = TRUE),
            se = sd / sqrt(n),
            CI = qnorm(1- 0.05/2) * se)

summary_3x$herb <- factor(summary_3x$herb,
                       levels = c("glyphosate", "cloransulam", "fomesafen"))

summary_3x
            
```



## PLOT

```{r}

ggplot(summary_3x, aes(x = mean*100, y = pop)) + 
  xlim(0, 100) + 
  geom_point(size = 2.5) + 
  geom_vline(xintercept = 90, size = 1, colour = "red") +
  geom_errorbar(aes(xmin = (mean*100) - (se*100), xmax = (mean*100) + (se*100), width = 0.3)) + 
  facet_grid( ~ herb, labeller = label_value) +
  labs(title = "Giant Ragweed Biomass Reduction - 3x POST", x = "Biomass Reduction (%)", y = "Population") + 
  theme_dark() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 35, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 25, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 15, colour = "black"),
         strip.text = element_text(face = "bold", size = 23, colour = "white")) +
  ggsave("RAW_POPxHERB_COMBINED_3x.jpeg", units="in", width = 15, height = 8, dpi=600)


```


