---
title: "ANOVA PALMER MORTALITY PRE - ALL HERBICIDES"
author: "Felipe A. Faleco"
date: "3/23/2020"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(car)
library(emmeans)
library(multcompView)
library(glmmTMB)
library(ggpubr)

palmer_pre <- read.csv("PRE.csv")
glimpse(palmer_pre)
```


# INTERACTION PLOT

```{r}

palmer_mean <- palmer_pre %>% group_by(pop, dose, herb) %>% summarize(mean_mort = mean(mort)) 

ggplot(aes(x = dose, y = mean_mort, group = herb, color = herb), data = palmer_mean) + geom_point() + geom_line() + theme_classic() + facet_wrap(~ pop)

```


# MODEL

```{r}
model <- glmmTMB(mort ~ herb*pop*dose + (1|run), data = palmer_pre, beta_family(link = "logit"))
```


# SUMMARY

```{r, echo=TRUE}
summary(model)
```


# ANOVA

```{r, echo=TRUE}

glmmTMB:::Anova.glmmTMB(model)

```


# EMM

```{r, echo=TRUE}

emm_herb.pop <- emmeans(model, ~ herb:pop, adjust = "tukey", type = "response", contr = "pairwise")

#emm_herb.pop

emm_herb.dose <- emmeans(model, ~ herb:dose, adjust = "tukey", type = "response", contr = "pairwise")

#emm_herb.dose

```


# PLOT

```{r, echo=TRUE}

plot(emm_herb.pop, adjust = "tukey", comparisons = TRUE)

plot(emm_herb.dose, adjust = "tukey", comparisons = TRUE)

```


# CLD

```{r, echo=TRUE}

CLD_herb.pop <- CLD(emm_herb.pop, comparisons = TRUE, Letters = letters, adjust = "tukey", reversed = TRUE)

CLD_herb.pop

CLD_herb.dose <- CLD(emm_herb.dose, comparisons = TRUE, Letters = letters, adjust = "tukey", reversed = TRUE)

CLD_herb.dose

```


# PLOTTING


```{r}
merged_data <- merge(palmer_pre,CLD_herb.pop) 

new_data <- CLD_herb.pop  %>% 
  right_join(palmer_pre, by="herb")

new_data
```


```{r, echo=TRUE}
ggplot(merged_data, aes(x = pop, y = mort*100,  color=mort, label=.group))  + theme_classic() +
  scale_color_gradient(low = "red", high = "grey") +
  geom_point(aes(x=pop, y = prop*100), color="black") +
  labs(title = "Palmer Mortality - PRE", x = "Population", y = "% Mortality") +
  facet_grid(~herb) + ylim(0, 105) + geom_jitter(width = 0.1, alpha=0.2) +
  #geom_text(nudge_y = c(7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7)) +
  geom_errorbar(aes(ymin = lower.CL*100, ymax = upper.CL*100), width = 0.2, color="black") +
  ggsave("figure.png", dpi=400)
```


```{r, echo=TRUE}
ggplot(new_data, aes(x = pop.x, y = prop*100, label = .group, color=mort*100)) + geom_point(size = 2) + theme_classic() +
  labs(title = "Palmer Mortality - PRE", x = "Population", y = "% Mortality") +
  facet_grid(~herb) + ylim(0, 105) + geom_jitter(width = 0.5) +
  geom_text(nudge_y = c(7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7)) +
  geom_errorbar(aes(ymin = lower.CL*100, ymax = upper.CL*100), width = 0.2)
```


```{r, echo=TRUE}
#ggplot(CLD_herb.dose, aes(x = dose, y = response*100, label = .group)) + geom_point(size = 2) + theme_classic() +
#  labs(title = "Palmer Mortality - PRE", x = "Dose", y = "% Mortality") +
#  facet_grid(~herb) + ylim(0, 105) +
#  geom_text(nudge_y = c(7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7)) +
#  geom_errorbar(aes(ymin = lower.CL*100, ymax = upper.CL*100), width = 0.2)
```