---
title: "RAW COUNTRED - WATERHEMP POP x HERB x RATE"
author: "Felipe A. Faleco"
date: "01/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(car)

```


# WHOLE DATA

```{r}

waterhemp <- read.csv("All PRE_Reduction.csv")

str(waterhemp)

waterhemp$run <- as.factor(waterhemp$run)

waterhemp$pop <- as.factor(waterhemp$pop)

waterhemp$Herbicide <- as.factor(waterhemp$Herbicide)

waterhemp$Rate <- as.factor(waterhemp$Rate)

waterhemp$rep <- as.factor(waterhemp$rep)

str(waterhemp)

```


# FILTERING TESTED ALL HERBICIDES

```{r}

tested_all_herbs <- waterhemp %>% filter(tested_all_herbs == "x")

```


# DATA SUMMARY

```{r}

summary <- tested_all_herbs %>% 
  group_by(pop, Herbicide, Rate) %>% 
  summarise(n = sum(!is.na(count_red)), 
            mean = mean(count_red, na.rm = TRUE), 
            sd = sd(count_red, na.rm = TRUE),
            se = sd / sqrt(n),
            CI = qnorm(1- 0.05/2) * se)

summary$herb <- factor(summary$Herbicide,
                       levels = c("atrazine", "fomesafen", "mesotrione", "metribuzin", "s-metolachlor"))

summary
            
```



# PLOT

```{r}

rate_labels <- c("0.5x" = "Rate: 0.5x", "1x" = "Rate: 1x", "3x" = "Rate: 3x")

ggplot(summary, aes(x = mean*100, y = pop)) + 
  xlim(0, 100) + 
  geom_point(size = 3) + 
  geom_vline(xintercept = 90, size = 1, colour = "red") +
  geom_errorbar(aes(xmin = (mean*100) - (se*100), xmax = (mean*100) + (se*100), width = 0.5)) + 
  facet_grid(Rate ~ Herbicide, labeller = labeller(Rate = rate_labels)) +
  labs(#title = "Waterhemp Plant Density Reduction - PRE", 
       x = "Plant Density Reduction (%)", 
       y = "Accession") + 
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 40, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 35, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 22, colour = "black"),
         strip.text = element_text(face = "bold", size = 30, colour = "black"),
         panel.spacing = unit(1, "lines")) +
  ggsave("RAW COUNTRED_POPxHERBxRATE.tiff", units="in", width = 18, height = 27, dpi = 600, compression = "lzw")

```

