---
title: "LOGIT BIORED - WATERHEMP"
author: "Felipe A. Faleco"
date: "01/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(car)
library(emmeans)
library(multcompView)
library(glmmTMB)
library(ggpubr)
library(Matrix)

```


# DATA

```{r}

data <- read.csv("All POST_Reduction.csv")

str(data)

data$run <- as.factor(data$run)

data$pop <- as.factor(data$pop)

data$Herbicide <- as.factor(data$Herbicide)

data$Rate <- as.factor(data$Rate)

data$rep <- as.factor(data$rep)

str(data)

```


# MODEL

```{r}

model <- glmmTMB(logit(bio_red) ~ Herbicide * Rate + (1|run) + (1|pop), data = data, family = "gaussian")


```


# SUMMARY

```{r, echo=TRUE}

summary(model)

```


# ANOVA

```{r, echo=TRUE}

glmmTMB:::Anova.glmmTMB(model, type = 2, test.statistic = "Chisq")


#The designations "type-II" and "type-III" are borrowed from SAS, but the definitions used here do not correspond precisely to those employed by SAS. Type-II tests are calculated according to the principle of marginality, testing each term after all others, except ignoring the term's higher-order relatives; so-called type-III tests violate marginality, testing each term in the model after all of the others. This definition of Type-II tests corresponds to the tests produced by SAS for analysis-of-variance models, where all of the predictors are factors, but not more generally (i.e., when there are quantitative predictors). Be very careful in formulating the model for type-III tests, or the hypotheses tested will not make sense.

#Be careful of type-III tests: For a traditional multifactor ANOVA model with interactions, for example, these tests will normally only be sensible when using contrasts that, for different terms, are orthogonal in the row-basis of the model, such as those produced by contr.sum, contr.poly, or contr.helmert, but not by the default contr.treatment. In a model that contains factors, numeric covariates, and interactions, main-effect tests for factors will be for differences over the origin. In contrast (pun intended), type-II tests are invariant with respect to (full-rank) contrast coding. If you don't understand this issue, then you probably shouldn't use Anova for type-III tests.


```


# EMM & CLD

```{r, echo=TRUE}

emm_herb_rate <- emmeans(model, ~ Herbicide|Rate, adjust = "tukey", type = "response", contr = "pairwise")

emm_herb_rate

CLD_emm_herb_rate <- if(requireNamespace("multcomp")) {
    multcomp::cld(emm_herb_rate$emmeans, alpha = 0.05, Letters=letters, adjust="tukey", reversed = TRUE)}

CLD_emm_herb_rate

```


# PLOT

```{r, echo=TRUE}


plot(emm_herb_rate, adjust = "tukey", comparisons = F, CIs = T, alpha = 0.05) + 
  geom_point(size = 2) +
  geom_text(aes(label = c("b", "a", "b", 
                          "c", "a", "b")),
            vjust = -0.8, size = 4) +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), limits = c(0, 1),
    labels = scales::percent_format(scale = 100, suffix = "")) +
  labs(#title = "Waterhemp Biomass Reduction - POST", 
       x = "Biomass reduction (%)", 
       y = "Herbicide") +
  facet_grid(~ Rate, labeller = label_both) +
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 18, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 18, colour = "darkgreen"), 
         axis.text= element_text(face = "bold", size = 14, colour = "black"),
         strip.text = element_text(face = "bold", size = 14, colour = "black"),
         panel.spacing = unit(1.0, "lines")) +
  ggsave("LOGIT Tukey HSD_HERBxRATE.tiff", units="in", width = 10, height = 4, dpi = 600, compression = "lzw")


```


