---
title: "PLANT SURVIVAL POP x HERB x RATE - GIANT RAGWEED"
author: "Felipe A. Faleco"
date: "11/172023"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(car)

```


# WHOLE DATA

```{r}

data <- read.csv("All POST_Reduction.csv")

str(data)

data$run <- as.factor(data$run)

data$pop <- as.factor(data$pop)

data$Herbicide <- as.factor(data$Herbicide)

data$Rate <- as.factor(data$Rate)

data$rep <- as.factor(data$rep)

str(data)

```


# DATA SUMMARY

```{r}

summary <- data %>% 
  group_by(pop, Herbicide, Rate) %>% 
  summarise(n = sum(!is.na(surv)), 
            mean = mean(surv, na.rm = TRUE), 
            sd = sd(surv, na.rm = TRUE),
            se = sd / sqrt(n),
            CI = qnorm(1- 0.05/2) * se)

#summary$herb <- factor(summary$Herbicide,
                       levels = c("Cloransulam", "Fomesafen", "Glyphosate"))

summary

```



# PLOT

```{r}

rate_labels <- c("1x" = "Rate: 1x", "3x" = "Rate: 3x")

ggplot(summary, aes(x = mean*100, y = pop)) + 
  geom_point(size = 4) + 
  geom_vline(xintercept = 50, size = 1, colour = "red") +
  geom_errorbar(aes(xmin = (mean*100) - (se*100), xmax = (mean*100) + (se*100), width = 0.4)) + 
  facet_grid(Rate ~ Herbicide, labeller = labeller(Rate = rate_labels))  +
  labs(#title = "Waterhemp Survivorship - POST", 
    x = "Plant Survival (%)", 
    y = "Accession") + 
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 50, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 45, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 28, colour = "black"),
         strip.text = element_text(face = "bold", size = 32, colour = "black"),
         panel.spacing = unit(1.5, "lines")) +
  ggsave("PLANT SURVIVAL_POPxHERBxRATE.tiff", units = "in", width = 22, height = 15, dpi = 600, compression = "lzw")
  

```


