---
title: "Dose response - Fall panicum"
author: "Jose"
date: "5/21/2021"
output: html_document
---

```{r, warning=F, message=FALSE}
library(tidyverse)
library(drc)
```

```{r}
fall = read_csv()
```

#DRC
```{r}
mod1 <- drm(control ~ rate, #variable ~ rate 
            Accession, #Accession or Pop.
            fct = l4(), #fct = drc function (l4(), l3(), W1.3(), etc)
            data = fall) #data set
summary(mod1)

#run and save the first mod, and then use it in the mselect function to estimate the best function for the data. Usually I run a first mod just to test the mselect function, and then if I have two drc functions (for ex. l3() and W1.3()) very close in the mselect results, I compare their parameters to check which is one is making more sense based on what I saw in the greenhouse. 

mselect(mod1, #previous mod
        list(l3(), l4(), W2.3(), W1.3(), W1.4(), W2.4()), #a list with drc functions that you want compare
        nested = TRUE, #the rest are the parameters that mselect will use to compare the functions
        sorted = c("IC", "Res var", "Lack of fit", "no"),
        linreg = TRUE, 
        icfct = AIC)

#Given the results of mselect, W2.3 would be the best function for these data.
model_control <- drm(control ~ rate, 
                     Accession, 
                     fct = W2.3(fixed=c(NA,NA,NA)), #this can be used to fix the parameters at a certain value, for example, if I want to fix the upper limit at 100, I'd insert 100 where there's the second NA. If I fix upper limit at 100, then the function won't estimate this parameter anymore. See below. 
                     data=fall)

#with summary you can check the parameters estimation and if they're significant or not.
summary(model_control)

#mod with the upper limit fixed at 100
model_control_2 <- drm(control ~ rate, 
                     Accession, 
                     fct = W2.3(fixed=c(NA,100,NA)), 
                     data=fall)

summary(model_control_2) #now the summary only have three values, because the upper limit was fixed at 100. So, drc didn't estimate it. It can be useful in case your lower or upper limit are being estimated into a value far from 0 or 100. But, since in model_control the upper limit was ok, I don't have to fix it. 

plot(model_control, col=c(3,2))

#Estimating the ED50 and 90. My will return NaN for the resistant because the control was low. 
ED(model_control, #mod
   c(50, 90), #ED values, it can be whatever you want, 10,20...
   type = "absolute", #for % control you can use absolute because all curves will start from 0. But for biomass in weight, where you have different upper limits (each population has a different biomass at 0), you should use "relative" instead of absolute. Because in this case the ED will be estimated from different upper limits.
   interval = "delta") #I've been using "delta"

#This can be used to compare the ED values. In my case will return an error because the function failed to estimate the ED50 and 90 before because of the low control. But you'll have the comparison of the population with an estimated resistance ratio, the std error, a t-value, and the p-value (if the difference between populations is siginificant or not)
EDcomp(model_control, c(50, 50), type = "absolute")

#This can be used to compare the parameters of the curve. For example, since the function failed to estimate the ED50 and 90, I used this function to compare the parameters of the two populations. With this function you can tell that the upper limit (the maximum control) was different between populations, or not. 
compParm(model_control, "b", "-") #difference in the parameter
compParm(model_control, "d", "-")
compParm(model_control, "e", "-")
```

#Theme for the plot
```{r}
fall_theme <- function(){  # Creating a function
  theme_bw() +  # Using pre-defined theme as base
  theme(axis.text.x = element_text(size = 12), #face = "bold"),  # Customizing axes text      
        axis.text.y = element_text(size = 12), #face = "bold"),
        axis.title = element_text(size = 12), #face = "bold"),  # Customizing axis title
        panel.grid = element_blank(),  # Taking off the default grid
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12, face = "italic"),  # Customizing legend text
        legend.title = element_text(size = 12, face = "bold"),  # Customizing legend title
        legend.position = c(.75, .55),  # Customizing legend position
        plot.caption = element_text(size = 8))  # Customizing plot caption
}                    
```

#Plotting with ggplot
```{r}
#Since drc doesn't work with ggplot directly, this can be used to get the results from drc and plot in ggplot. 

#First create a serie of new data, one general where you have to replace the 254 by your highest rate
newdata <- expand.grid(rate = exp(seq(log(0.5), log(254), length=254)))
#A new data for each Accession, keep in mind how you named rate and accession in the column, and the population names in the data frame, they should be the same here. 
newdata1 <- data.frame(Accession = c("ALS-susceptible"), newdata)
newdata2 <- data.frame(Accession = c("ALS-resistant"), newdata)

#Here you bind the two data frames and create a new one - nd
nd <- rbind(newdata1, newdata2)

#Here you predict the values based on your model, depending on how high the highest rate is, it can take minutes to predict. Glyphosate is a pain. 
pm <- predict(model_control, newdata = nd, interval="confidence")

#Just run
nd$p <- pm[,1]
nd$pmin <- pm[,2]
nd$pmax <- pm[,3]

#Here you have to replace fall by your data frame name so you can create a new column with the rates that were created before. This part is confusing and I just follow as it's. 
fall$rate0 <- fall$rate
fall$rate0[fall$rate0 == 0] <- 0.5

#Here I just calculate the means of control to add as points in the plot. You can do this in ggplot as well, but I just think this is easier.
medias <- aggregate(control ~ rate*Accession, FUN = mean, data = fall)

ggplot(fall, aes(x = rate, y = control, shape = Accession, linetype = Accession)) + 
  geom_line(data = nd, aes(x = rate, y = p, linetype = Accession)) + #geom_line will take the data tha you created in this chunk to plot the lines, so mind the name of the data set and the aesthestics. 
  geom_point(data = medias, aes(rate, control, shape = Accession, linetype = Accession), 
             size = 3)+
  #scale_x_log10() + in case you want log scale
  labs(x = bquote ('Nicosulfuron g ai'~ha^-1), y = "Visual control (%)") +
  theme(axis.line = element_line(colour = "black", 
                                  size = 0.1, linetype = "solid"))+
  scale_linetype_manual(values = c("solid", "dashed"))+
  fall_theme() 

ggsave("control2.tiff",  width = 5, height = 5, units = "in", dpi = 1000)
```


