---
title: "Giant Ragweed Fomesafen DR"
author: "Felipe Faleco"
date: "10/25/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(drc)
library(doBy)
library(plotrix)

```


# READ DATA

```{r}

data <- read.csv("Data.csv")

str(data)


mean.AT2 <- summaryBy(biomass ~ dose + pop, data = subset(data, pop=="AT2"))

mean.AT8.edge<- summaryBy(biomass ~ dose + pop, data = subset(data, pop=="AT8-EDGE"))

```


# MODEL LL.4

```{r}

model.LL4<- drm(biomass ~ dose, pop, fct = LL.4(),  data = data)

summary(model.LL4) 

plot(model.LL4)

```


# MODEL LL.3

```{r, warning=FALSE}


model.LL3<- drm(biomass ~ dose, pop, fct = LL.3(),  data = data, type = "continuous")

summary(model.LL3)

plot(model.LL3)

```



# ED50 ABSOLUTE VS RELATIVE

```{r}

# In a LL.3 model (lower limit = 0) the relative ED50 and absolute ED50 are the same. Below the example calculated for the curve AT2. 
# Note that, to calculate the absolute, we need to specify the 50% of the upper limit of AT2 (1.104744 * 0.5 = 0.552372). 

ED(model.LL3, c(50), clevel = "AT2", type = "relative") 

ED(model.LL3, c(0.552372), clevel = "AT2", type = "absolute")




# However, when the lower limit is not exactly zero, like in our LL.4, we can start to see a difference between the relative ED50 and absolute ED50, although in our case the lower limit not being to far from zero (even not statistically significant), this difference between relative and absolute is not so big and probably also not significant.
# Note that the 50% of the AT2 upper limmit here is different than the previous because in the LL.4 model the upper limit 

ED(model.LL4, c(50), clevel = "AT2", type = "relative") 

ED(model.LL4, c(0.54903125), clevel = "AT2", type = "absolute")



```


# ED50 RI ABSOLUTE VS RELATIVE

```{r}

# ED50 RI for the LL3 model yields the same using relative or absolute.

EDcomp(model.LL3, c(50, 50), type = "relative", interval = "none")

EDcomp(model.LL3, c(0.552372, 0.701183), type = "absolute", interval = "none")



# ED50 RI for the LL4 model yields the different when using relative or absolute, although in our case still very close becase in the LL.4 lower limit still very close to zero (not statistically different).

EDcomp(model.LL4, c(50, 50), type = "relative", interval = "none")

EDcomp(model.LL4, c(0.54903125, 0.7019742), type = "absolute", interval = "none")


```





