---
title: "Giant Ragweed Fomesafen DR"
author: "Felipe Faleco"
date: "10/25/2021"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(drc)
library(doBy)
library(plotrix)

```


# READ DATA

```{r}

data <- read.csv("Data.csv")

str(data)



fun <- function(x){
  c( mean = mean(x), VAR = var(x), SD = sd(x), SE = std.error(x), n = length(x))
}

summary.AT2 <- summaryBy(cbind(biomass, surv) ~ dose + pop, data = subset(data, pop=="AT2"),
          FUN=fun)

summary.AT2


summary.AT8.EDGE<- summaryBy(cbind(biomass, surv) ~ dose + pop, data = subset(data, pop=="AT8-EDGE"),
          FUN=fun)

summary.AT8.EDGE


```



# MODEL LL.4

```{r}

model.LL4<- drm(biomass ~ dose, pop, fct = LL.4(),  data = data)



modelFit(model.LL4) # higher the p-value, better.

summary(model.LL4) 

# c: lower limit (models with negative lower limit are biologically impossible. E.g., negative biomass, negative % biomass reduction, or negative % control)

# d: upper limit (models where the response variable is in %, upper limit bigger than 100% are biologically impossible. E.g., % biomass reduction, % control)

# b: slope around e (inflection point)

# e: e (inflection point). Represents the dose producing a response halfway between the u and l parameters (ED50)

```



# MODEL SELECTION

```{r, warning=FALSE}

mselect(model.LL4,  list(L.3(), l4(), L.5(), LL.2(), LL.3(), LL.5(), W1.3(), W1.4(), W2.4(), baro5()), linreg = T) 

#LL.3 better option here (lower IC, which actually is AIC (default)). W1.3 could also be used, but since it is a asymmetrical model, I would give preference to LL.3 In symmetrical models, the parameter e and relative ED50 are identical, that is, they both indicate the dose that reduces the response midway between the upper and lower limits. In asymmetrical models, however, the parameter e does not have the same meaning as in symmetrical models, even though it is still the location of the inflection point. For assymetrical models, ED50 should be estimated as "absolute" and not relative.



model.LL3<- drm(biomass ~ dose, pop, fct = LL.3(),  data = data, type = "continuous")



modelFit(model.LL3)

summary(model.LL3) # NO parameter c (lower limit). It means lower limit was set to zero.



anova(model.LL3, model.LL4) # p-value > 0.05 means that there is no difference between models. Therefore, we can use model LL.3

```



# ED50 AND ED 90

```{r}

ED(model.LL3, c(50, 90), type = "relative") 

# Estimated doses required for ED50, and ED90. Estimation of ED90 is statistically less accurate and often subject to high variance. Therefore, is better to use ED50.

```


# ED 50 RI AND PARAMETERS STUDENT T-TEST COMPARISONS

```{r}

EDcomp(model.LL3, c(50, 50), type = "relative", interval = "none")

# Use (type = absolute) if curves are non-parallel (differs significantly in upper or lower limits; or both)
# Use (interval = delta) if asymmetrical models, like fiveparameter log-logistic, Gompertz, and Weibull. NOT SURE ABOUT THIS ONE


# Comparing b parameter (slope)
compParm(model.LL3, strVal = "b", operator = "-")


# Comparing d parameter (upper limit)
compParm(model.LL3, strVal = "d", operator = "-")

# Comparing e parameter (ED50)
compParm(model.LL3, strVal = "e", operator = "-") #here comparing the difference, and not the ratio like in the EDcomp


```



# PLOT

```{r}

tiff(file = "C:/Users/felip/OneDrive - UW-Madison/Documents/GitHub/FFaleco/PhD Projects/Giant Ragweed/Dose Response/Fomesafen/Dose-response curve.tiff",
     width = 6, height = 4, units="in", 
     res = 1000)


plot(model.LL3,
     type = "average",
     xlab = expression("Herbicide dose (g ai ha)" ^-1),
     ylab = expression("Aboveground biomass (g plant)" ^-1),
     col = c("red", "darkgreen"),
     pch = c(19, 17),
     cex = 1,
     cex.axis = 1,
     cex.lab = 1,
     lwd = 1)

abline(v = 263, 
       lwd = 2, 
       lty = "twodash",
       col = "black")

text(x = 950, y = 0.8, 
     labels = expression("1x dose: 263 g ai ha" ^-1),
     cex = 0.8,
     col = "black",
     font = 2)

dev.off()

```







