---
title: "LOGIT COUNTRED - PALMER"
author: "Felipe A. Faleco"
date: "01/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(car)
library(emmeans)
library(glmmTMB)

```


# DATA

```{r}

palmer <- read.csv("All PRE_Reduction.csv")

str(palmer)

palmer$run <- as.factor(palmer$run)

palmer$pop <- as.factor(palmer$pop)

palmer$herb <- as.factor(palmer$herb)

palmer$Dose <- as.factor(palmer$Dose)

palmer$rep <- as.factor(palmer$rep)

str(palmer)

```


# MODEL

```{r}

model <- glmmTMB(logit(count_red) ~ pop * herb * Dose + (1|run), data = palmer, family = "gaussian")

```


# SUMMARY

```{r, echo=TRUE}

summary(model)

```


# ANOVA

```{r, echo=TRUE}

glmmTMB:::Anova.glmmTMB(model)

```


# EMM & CLD

```{r, echo=TRUE}

emm_pop_herb <- emmeans(model, ~ pop|herb, adjust = "tukey", type = "response", contr = "pairwise")

emm_pop_herb

CLD_emm_pop_herb <- if(requireNamespace("multcomp")) {
    multcomp::cld(emm_pop_herb$emmeans, alpha = 0.05, Letters=letters, adjust="tukey", reversed = T)}

CLD_emm_pop_herb



emm_herb_Dose <- emmeans(model, ~ herb|Dose, adjust = "tukey", type = "response", contr = "pairwise")

emm_herb_Dose

CLD_emm_herb_Dose <- if(requireNamespace("multcomp")) {
    multcomp::cld(emm_herb_Dose$emmeans, alpha = 0.05, Letters=letters, adjust="tukey", reversed = T)}

CLD_emm_herb_Dose

```


# PLOT

```{r, echo=TRUE}

plot(emm_pop_herb, adjust = "tukey", comparisons = F, alpha = 0.05) + 
  geom_point(size = 2.5) +
  facet_grid( ~ herb, labeller = label_value) +
  geom_text(aes(label = c("c", "b", "a", 
                          "a", "a", "a", 
                          "a", "a", "a", 
                          "a", "a", "a", 
                          "a", "a", "a")),
            vjust = -1, size = 5) +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), limits = c(0, 1),
    labels = scales::percent_format(scale = 100, suffix = "")) +
  labs(title = "Palmer Count Reduction - PRE", 
       x = "Plant Density Reduction (%)", 
       y = "Accession") + 
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 28, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 22, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 15, colour = "black"),
         strip.text = element_text(face = "bold", size = 18, colour = "black"),
         panel.spacing = unit(1.0, "lines")) +
  ggsave("LOGIT Tukey HSD_POPxHERB.jpeg", units="in", width = 15, height = 3, dpi = 600)




plot(emm_herb_Dose, adjust = "tukey", comparisons = F, alpha = 0.05) + 
  geom_point(size = 2.5) +
  facet_grid( ~ Dose, labeller = label_both) +
  geom_text(aes(label = c("c", "b", "ab", "ab", "a", 
                          "b", "a", "a", "a", "a", 
                          "b", "a", "a", "a", "a")),
            vjust = -1, size = 5) +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), limits = c(0, 1),
    labels = scales::percent_format(scale = 100, suffix = "")) +
  labs(title = "Palmer Count Reduction - PRE", 
       x = "Plant Density Reduction (%)", 
       y = "Herbicide") + 
  theme_bw() + 
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 28, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 22, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 15, colour = "black"),
         strip.text = element_text(face = "bold", size = 18, colour = "black"),
         panel.spacing = unit(1.0, "lines")) +
  ggsave("LOGIT Tukey HSD_HERBxDOSE.jpeg", units="in", width = 15, height = 4, dpi = 600)

```

