---
title: "Waterhemp MIs GH 2,4-D Percent Biomass"
author: "Felipe Faleco"
date: "09/24/2024"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(drc)
library(doBy)
library(plotrix)
library(dplyr)

```


# CONFIRMING RESISTANCE


## READ DATA

```{r}

data <- read.csv("Data Sheet_2,4-D_GH.csv")

str(data)


data_24D <- data %>% filter(herb == "2,4D")


fun <- function(x){
  c( mean = mean(x, na.rm = T), VAR = var(x, na.rm = T), SD = sd(x, na.rm = T), SE = std.error(x, na.rm = T), n = length(x))
}

summary.24D <- summaryBy(cbind(percent_bio) ~ pop + rate, data = subset(data_24D),
          FUN=fun)


```



## MODEL LL.4

```{r}

model.LL4 <- drm(percent_bio ~ rate, pop, fct = LL.4(), data = data_24D, type = "continuous")


plot(fitted(model.LL4), residuals(model.LL4))

                
modelFit(model.LL4) # higher the p-value, better.

summary(model.LL4) 

# c: lower limit (models with negative lower limit are biologically impossible. E.g., negative biomass, negative % biomass reduction, or negative % control)

# d: upper limit (models where the response variable is in %, upper limit bigger than 100% are biologically impossible. E.g., % biomass reduction, % control)

# b: slope around e (inflection point)

# e: e (inflection point). Represents the dose producing a response halfway between the u and l parameters (ED50)

```



## MODEL SELECTION

```{r, warning=FALSE}

getMeanFunctions() # To get the most used functions when fitting dose-response curves.


mselect(model.LL4,  list(LL.2(), LL2.2(), LL.3(), LL.3u(), LL2.3(), LL2.3u(), LL.4(), LL2.4(), LL.5(), LL2.5(), W1.2(), W2.2(), W1.3(), W1.3u(), W2.3(), W2.3u(), W1.4(), W2.4()))


# Lower IC, which actually is AIC (default), indicates the best model to be used. On the other hand, the highest the Lack of Fit, better the model. The two-, three-, and four-parameter log-logistic models are are symmetrical around the inflection point (parameter "e") while others (e.g. fiveparameter log-logistic, Gompertz, and Weibull) are asymmetrical. In symmetrical models, the parameter "e" and relative ED50 are identical, that is, they both indicate the dose that reduces the response midway between the upper and lower limits. In asymmetrical models, however, the parameter "e" does not have the same meaning as in symmetrical models, even though it is still the location of the inflection point. Therefore, in asymmetrical models, ED50 should be estimated as "absolute" and not relative.


model.W1.2 <- drm(percent_bio ~ rate, pop, fct = W1.2(),  data = data_24D, type = "continuous")

plot(fitted(model.W1.2), residuals(model.W1.2))

qqnorm(residuals(model.W1.2))


modelFit(model.W1.2)

summary(model.W1.2)



anova(model.W1.2, model.LL4) # p-value > 0.05 means that there is no difference between models. Therefore, we can use model W1.2

```



## ED50

```{r}

#ED(model.W1.3, c(50), type = "relative", interval = "delta")


ED50.A82 <- ED(model.W1.2, 0.5, clevel = "A82", type = "absolute", interval = "delta")

ED50.A101 <- ED(model.W1.2, 0.5, clevel = "A101", type = "absolute", interval = "delta")

ED50.A103 <- ED(model.W1.2, 0.5, clevel = "A103", type = "absolute", interval = "delta")

ED50.A75 <- ED(model.W1.2, 0.5, clevel = "A75", type = "absolute", interval = "delta")

# In this case, fitting relative and absolute resulted in the same ED50. Perhaps because W1.3 has a lower limit = 0. In simulations using the W1.4, then the relative and absolute ED50 are different. 

```


## ED 50 RI AND PARAMETERS STUDENT T-TEST COMPARISONS

```{r}

#EDcomp(model.W1.3, c(50, 50), type = "relative", interval = "none", reverse = F)


EDcomp(model.W1.2, c(0.5, 0.5), 
       compMatch = c("A101", "A82"), type = "absolute", interval = "none", reverse = F)


EDcomp(model.W1.2, c(0.5, 0.5), 
       compMatch = c("A103", "A82"), type = "absolute", interval = "none", reverse = F)


EDcomp(model.W1.2, c(0.5, 0.5), 
       compMatch = c("A75", "A82"), type = "absolute", interval = "none", reverse = F)




# Comparing b parameter (slope)
compParm(model.W1.2, strVal = "b", operator = "-")


# Comparing d parameter (upper limit)
compParm(model.W1.2, strVal = "d", operator = "-")


# Comparing e parameter (Infletion Point)
compParm(model.W1.2, strVal = "e", operator = "-") # Remember that for assymetric models, the paramenter"e" does not reflect the ED50. 


```



##SAVE TIFF

```{r}

tiff(file="C:/Users/felip/OneDrive - UW-Madison/Documents/GitHub/FFaleco/PhD/PhD Projects/Waterhemp/Metabolism Inhibitors/GH/2,4-D/2,4-D_Absolute ED/GH_2,4D Only_All Pops_DR Percent Bio.tiff",
     width = 10, height = 8, units = "in", res = 600, compression = "lzw")


par(mar = c(5,5,1,1))


plot(model.W1.2,
     type = "average",
     xlab = expression(paste("2,4-D rate (g ae ha"^-1, ")")),
     ylab = expression(paste("Biomass (x 100%)")),
     ylim = c(0, 1),
     #broken = T,
     col = c("darkgreen", "red", "navy", "orange"),
     pch = c(19, 17, 15, 18),
     cex = 1.5,
     cex.axis = 1.5,
     cex.lab = 2.0,
     cex.legend = 1.8,
     legendPos = c(15000, 1),
     lwd = 1.5)



points(x = c(ED50.A82[1, 1], 
             ED50.A101[1, 1],
             ED50.A103[1, 1],
             ED50.A75[1, 1]),
       y = c(0.5, 0.5, 0.5, 0.5),
       pch = 8,
       cex = 1.3)



#abline(v = 1065, 
       #lwd = 2, 
       #lty = "twodash",
       #col = "black")



#text(x = 4500, y = 2.0, 
     #labels = expression(paste("ED"[50] ~ "A101 = 297.6 ("%+-% "61.7)" ^A)),
     #cex = 1.0,
     #col = "black",
     #font = 2)


#text(x = 4200, y = 1.8, 
     #labels = expression(paste("ED"[50] ~ "A75 = 111.6 ("%+-% "25.8)" ^B)),
     #cex = 1.0,
     #col = "black",
     #font = 2)


#text(x = 4200, y = 1.6, 
     #labels = expression(paste("ED"[50] ~ "A82 = 104.7 ("%+-% "21.5)" ^B)),
     #cex = 1.0,
     #col = "black",
     #font = 2)


#text(x = 4200, y = 1.4, 
     #labels = expression(paste("ED"[50] ~ "A103 = 55.2 ("%+-% "12.3)" ^C)),
     #cex = 1.0,
     #col = "black",
     #font = 2)


#text(x = 3200, y = 0.7, 
     #labels = expression("1x rate: 1065 g ae ha" ^-1),
     #cex = 1.0,
     #col = "black",
     #font = 2)


dev.off()


```


