---
title: "Waterhemp_GLU_Dose Response"
author: "Felipe Faleco"
date: "11/8/2021"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(drc)
library(doBy)
library(plotrix)

```


# READ DATA

```{r}

data <- read.csv("Data.csv")

str(data)



fun <- function(x){
  c( mean = mean(x), VAR = var(x), SD = sd(x), SE = std.error(x), n = length(x))
}

summary.BROK <- summaryBy(cbind(biomass, surv) ~ dose + pop, data = subset(data, pop=="BROK"),
          FUN=fun)


summary.A66 <- summaryBy(cbind(biomass, surv) ~ dose + pop, data = subset(data, pop=="A66"),
          FUN=fun)


summary.A82<- summaryBy(cbind(biomass, surv) ~ dose + pop, data = subset(data, pop=="A82"),
          FUN=fun)

```



# MODEL LL.4

```{r}

model.LL4<- drm(biomass ~ dose, pop, fct = LL.4(),  data = data)



modelFit(model.LL4) # higher the p-value, better.

summary(model.LL4) 

# c: lower limit (models with negative lower limit are biologically impossible. E.g., negative biomass, negative % biomass reduction, or negative % control)

# d: upper limit (models where the response variable is in %, upper limit bigger than 100% are biologically impossible. E.g., % biomass reduction, % control)

# b: slope around e (inflection point)

# e: e (inflection point). Represents the dose producing a response halfway between the u and l parameters (ED50)

```



# MODEL SELECTION

```{r, warning=FALSE}

mselect(model.LL4,  list(L.3(), L.4(), L.5(), LL.2(), LL.3(), LL.5(), W1.3(), W1.4(), W2.4(), baro5()), linreg = T) 

# In asymmetrical models, the parameter e does not have the same meaning as in symmetrical models, even though it is still the location of the inflection point. For assymetrical models, ED50 should be estimated as "absolute" and not relative.


model.W1.3 <- drm(biomass ~ dose, pop, fct = W1.3(),  data = data, type = "continuous")


modelFit(model.W1.3)

summary(model.W1.3) # NO parameter c (lower limit). It means lower limit was set to zero.



anova(model.W1.3, model.LL4) # p-value > 0.05 means that there is no difference between models. Therefore, we can use model LL.3

```



# ED50 AND ED 90

```{r}

ED(model.W1.3, c(50, 90), type = "relative") 


ED(model.W1.3, (summary(model.W1.3)$coef["d:BROK", "Estimate"]* 0.5), 
               clevel = "BROK", 
               type = "absolute")

ED(model.W1.3, (summary(model.W1.3)$coef["d:A66", "Estimate"]* 0.5), 
               clevel = "A66", 
               type = "absolute")

ED(model.W1.3, (summary(model.W1.3)$coef["d:A82", "Estimate"]* 0.5), 
               clevel = "A82", 
               type = "absolute")


# Estimated doses required for ED50, and ED90. Estimation of ED90 is statistically less accurate and often subject to high variance. Therefore, is better to use ED50.

```


# ED 50 RI AND PARAMETERS STUDENT T-TEST COMPARISONS

```{r}

EDcomp(model.W1.3, c(50, 50), type = "relative", interval = "none", reverse = T)
# Altought being an assymetric model (Weidbull), here I can use relative comparison because the ED50s were the same for relative and absolute. I believe because lower limit = 0



# Comparing b parameter (slope)
compParm(model.W1.3, strVal = "b", operator = "-")


# Comparing d parameter (upper limit)
compParm(model.W1.3, strVal = "d", operator = "-")

# Comparing e parameter (ED50)
compParm(model.W1.3, strVal = "e", operator = "-") #here comparing the difference, and not the ratio like in the EDcomp


```



# PLOT

```{r}

plot(model.W1.3)


plot(model.W1.3,
     type = "average",
     xlab = expression("Herbicide dose (g ai ha)" ^-1),
     ylab = expression("Aboveground biomass (g plant)" ^-1),
     col = c("red", "darkgreen", "green"),
     pch = c(19, 17, 18),
     cex = 1,
     cex.axis = 1,
     cex.lab = 1,
     lwd = 1)

abline(v = 650, 
       lwd = 2, 
       lty = "twodash",
       col = "black")

text(x = 2000, y = 1, 
     labels = expression("1x dose: 650 g ai ha" ^-1),
     cex = 0.8,
     col = "black",
     font = 2)


```



#SAVE TIFF

#```{r}

tiff(file="C:/Users/felip/OneDrive - UW-Madison/Documents/GitHub/FFaleco/PhD Projects/Giant Ragweed/Dose Response/Fomesafen/Dose-response curve.tiff",
width=6, height=4, units="in", res=1000, compression = "lzw")

plot(model.LL3,
     type = "average",
     xlab = expression("Herbicide dose (g ai ha)" ^-1),
     ylab = expression("Aboveground biomass (g plant)" ^-1),
     col = c("red", "darkgreen"),
     pch = c(19, 17),
     cex = 1,
     cex.axis = 1,
     cex.lab = 1,
     lwd = 1)

abline(v = 263, 
       lwd = 2, 
       lty = "twodash",
       col = "black")

text(x = 950, y = 0.8, 
     labels = expression("1x dose: 263 g ai ha" ^-1),
     cex = 0.8,
     col = "black",
     font = 2)

dev.off()

```