---
title: "SURVIVORSHIP - ROK-19"
author: "Felipe A. Faleco"
date: "12/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(car)
library(doBy)
library(plotrix)

```


# WHOLE DATA

```{r}

data <- read.csv("Data_biored.csv")

str(data)

data$run <- as.factor(data$run)

data$pop <- as.factor(data$pop)

data$herb <- as.factor(data$herb)

data$dose <- as.factor(data$dose)

data$rep <- as.factor(data$rep)

str(data)

```



# DATA SUMMARY

```{r}

fun <- function(x){
  c(n = sum(!is.na(x)),
    mean = mean(x, na.rm = TRUE), 
    VAR = var(x, na.rm = TRUE), 
    SD = sd(x, na.rm = TRUE), 
    SE = std.error(x, na.rm = TRUE),
    CI = qnorm(1- 0.05/2) * std.error(x))
}


summary <- summaryBy(cbind(biomass,surv) ~ pop + herb + dose, data = data,
          FUN=fun)

```



# PLOT

```{r}

dose_labels <- c("1x" = "Dose: 1x", "3x" = "Dose: 3x")

ggplot(summary, aes(x = surv.mean*100, y = pop)) +
  xlim(0, 100) + 
  geom_point(size = 1) + 
  geom_vline(xintercept = 50, size = 0.5, colour = "red") +
  geom_errorbar(aes(xmin = (surv.mean*100) - (surv.SE*100), xmax = (surv.mean*100) + (surv.SE*100), width = 0.05)) + 
  facet_grid(dose ~ herb, labeller = labeller(dose = dose_labels))  +
  labs(title = "ROK-19 Survivorship - POST", x = "Survivorship (%)", y = "Accession") + 
  theme_bw() +
  theme (plot.title = element_text(face = "bold", hjust = 0.5, size = 12, colour = "darkgreen"), 
         axis.title = element_text(face = "bold", size = 10, colour = "darkgreen"), 
         axis.text = element_text(face = "bold", size = 6, colour = "black"),
         strip.text = element_text(face = "bold", size = 8, colour = "black"),
         panel.spacing = unit(0.5, "lines")) +
  ggsave("SURVIVORSHIP_ROK-19.jpeg", units = "in", width = 8, height = 4, dpi = 600)

```


